### ISSUE TITLE
Net::XMPP::XEP Not Found

### ISSUE THREAD

**Issue by aizukanne** [thiagodk/goip-sms-server#1]
Hello,

I get this error when XMPP is enabled 

> Can't  locate Net/XMPP/XEP.pm in @INC (you may need to install the Net::XMPP::XEP module)

cpanm is unable to find and install Net::XMPP::XEP module. It reports 

> ! Finding Net::XMPP::XEP on cpanmetadb failed.
> ! Finding Net::XMPP::XEP () on mirror http://www.cpan.org failed.
> ! Couldn't find module or a distribution Net::XMPP::XEP

Kindly advice hoe to proceed

**Comment by thiagodk** [comment]
Hello, it's a custom made Perl module that implents Ad-Hoc commands. I just forgot to include that in my commits, was now added by commit 9da5c7101e6518cde1a6b7f20cc881ea7687f1c4
