### ISSUE TITLE
Problems Starting Server

### ISSUE THREAD

**Issue by nacbooth** [thiagodk/goip-sms-server#3]
If you have a moment I'd appreciate a few pointers to get this working:

This is running on a recent Raspberry Pi, "Raspbian GNU/Linux 8 (jessie)" with perl: (v5.20.2)

The second time I start the server, it stops fairly quickly  with a message about the database (having created a file in the expected place the first time).  

=================================

DBD::CSV::db do failed:
Execution ERROR: Cannot create table sms: Already exists at /usr/lib/arm-linux-gnueabihf/perl5/5.20/DBI/DBD/SqlEngine.pm line 1589.
 called from ./sms-server.pl at 359.

 [for Statement "CREATE TABLE sms (authid TEXT, cid_number TEXT, cid_name TEXT, msg_date INTEGER, tz INTEGER, message TEXT)"] at ./sms-server.pl line 359.

Execution ERROR: Cannot create table sms: Already exists at /usr/lib/arm-linux-gnueabihf/perl5/5.20/DBI/DBD/SqlEngine.pm line 1589.
 called from ./sms-server.pl at 359.

=================================

If I add "IF NOT EXISTS"  at that line, it still barfs with:

=================================

Can't find column definitions! at /usr/share/perl5/SQL/Statement.pm line 88.
DBD::CSV::db do failed: Can't find column definitions! [for Statement "CREATE TABLE IF NOT EXIST sms (authid TEXT, cid_number TEXT, cid_name TEXT, msg_date INTEGER, tz INTEGER, message TEXT)"] at ./sms-server.pl line 359.
Can't find column definitions! at ./sms-server.pl line 359.

=================================

Finally, can you give an example of the formatting for a config file - the command line I've formulated is somewhat unwieldly!
$ ./sms-server.pl  --log-out=/var/log/smsgateway/sms_gateway.log --log-err=/var/log/smsgateway/sms_error.log --pid-file=/var/spool/smsgate.pid --server-host=192.168.1.202 server-port=44444 --use-csv --csv-dir=/var/log/smsgateway --csv-file=/var/log/smsgateway/sms-messages.db --use-smtp --smtp-host=127.0.0.1 --mail-addr-local=nicholas@spookhollow.net  --smtp-domain=spookhollow.net --add-authentication=goip:goip --daemon

**Comment by nacbooth** [comment]
I'm using MySQL now, so this is pretty much moot.  Still left with a problem connecting to SMTP server, but it's an interesting learning experience.  Hopefully I'll get this working eventually.  
Thanks for the code.

**Comment by thiagodk** [comment]
CSV bug is now fixed, it was being created in wrong path.
